name: AnonymousMasks
version: '5.4.3'
main: dev.imfound.anonymousmasks.AnonymousMasks
authors: [ ImFound ]
description: AnonymousMasks
website: ImFound.dev
softdepend:
  - TAB
commands:
  anonymousmasks:
    description: Comando AM5
    aliases: [am, anonymousmask, am5]